export const LIST = {
  LIST_BEGIN: 'BUILD LIST BEGIN',
  SET_PRODUCT_LIST: 'SET PRODUCT LIST',
  SET_PAGE_DATA: 'SET PAGE DATA',
  UPDATE_PRODUCT_LIST: 'UPDATE PRODUCT LIST',
  SET_ERROR_PRODUCT_LIST: 'SET ERROR PRODUCT LIST'
}

export const ERROR_MESSAGE = "Something's please come back later"